### PR TITLE
Don't shadow `Base` functions

### PR DESCRIPTION
**Pull request by rejuvyesh**
We should be extending `Base.step` and `Base.reset` (I'm on Julia v1.7.2). I would recommend `Squash and Merge` for this PR because I accidentally added and reverted a local thing I was testing.

### CODE REVIEW

**Comment by rejuvyesh** [comment]
Also would be great if you could change your security settings to allow my (and other contributors') PRs to run CI!

**Comment by simon-lc** [comment]
Thanks for your help!

**Comment by simon-lc** [comment]
@rejuvyesh Hi Jayesh, I am sorry I am very new to this, we have this setting for the contributors' PRs:
Screenshot from 2022-03-07 15-22-37
I am not sure but we had a check in CI.yml that might have prevented CI to test your PR. I removed it so hopefully this make things easier on your side!
Please tell me if I need to do anything else to ease the process

**Comment by rejuvyesh** [comment]
I think changing it require approval for "first-time contributors" is recommended option. This way most accounts that have been using GitHub for a while, when they make a PR, should be able to have CI run for their PR as well. But just for me, your selected option is fine too!

**Comment by simon-lc** [comment]
Thanks for the explanation! I've just made the change

**Pull request merged**
