### PR TITLE
Shift most test from FiniteDiff to ForwardDiff

### PR DESCRIPTION
**Pull request by janbruedigam**

### CODE REVIEW

**Comment by rejuvyesh** [comment]
Any estimates for difference in eval time with ForwardDiff vs FiniteDiff?

**Comment by janbruedigam** [comment]
Haven't checked yet in detail, feels a bit faster, but I could also be completely wrong

**Comment by rejuvyesh** [comment]
Julia v1.8 (beta) shows timing information in tests as well.

Current master:
```
Integrator              |    7      7  9.7s
  FiniteDiff comparison |    7      7  9.4s
```

This PR:
```
Integrator               |    7      7  9.1s
  ForwardDiff comparison |    7      7  8.8s
```

**Comment by thowell** [comment]
Thanks for the PR Jan! 

@rejuvyesh what is the correct way to include dependencies for the tests? I was under the impression that now there should be a test/Project.toml file: https://pkgdocs.julialang.org/v1/creating-packages/#Test-specific-dependencies-in-Julia-1.2-and-above 

Also, what are your thoughts on FiniteDiff vs ForwardDiff for the tests? Ideally we would just support one.

**Comment by rejuvyesh** [comment]
> Test dependencies

Yeah, `test/Project.toml` is the way to go! 

> FiniteDiff vs ForwardDiff for tests

Main thing I am not fully sure about is why do you have to define custom gradient/jacobian functions if AD like ForwardDiff already works? I would assume for performance/efficiency? In that case best to compare against proper AD like ForwardDiff. However, if you see that you are defining gradients for functions where AD like ForwardDiff is not going to work, then supporting FiniteDiff makes sense.

**Comment by janbruedigam** [comment]
Thanks for the clarification @rejuvyesh ! I've readded the test Project.toml.
Moving the remaining tests to ForwardDiff will require some additional work with rotations and mrps, so I would revisit that at a later stage. 
I updated the test tolerances, so if tests keep failing they can be loosened again.

**Pull request merged**
